// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [{type: 'autogenerated', dirName: 'intro'}],
      link: {type: 'doc', id: 'intro/index'},
    },
    {
      type: 'category',
      label: 'Foundations',
      items: [{type: 'autogenerated', dirName: 'foundations'}],
      link: {type: 'doc', id: 'foundations/index'},
    },
    {
      type: 'category',
      label: 'ROS 2',
      items: [{type: 'autogenerated', dirName: 'ros2'}],
      link: {type: 'doc', id: 'ros2/index'},
    },
    {
      type: 'category',
      label: 'Digital Twin',
      items: [{type: 'autogenerated', dirName: 'digital-twin'}],
      link: {type: 'doc', id: 'digital-twin/index'},
    },
    {
      type: 'category',
      label: 'Perception Systems',
      items: [{type: 'autogenerated', dirName: 'perception'}],
      link: {type: 'doc', id: 'perception/index'},
    },
    {
      type: 'category',
      label: 'Motion Planning',
      items: [{type: 'autogenerated', dirName: 'motion-planning'}],
      link: {type: 'doc', id: 'motion-planning/index'},
    },
    {
      type: 'category',
      label: 'Reinforcement Learning',
      items: [{type: 'autogenerated', dirName: 'reinforcement-learning'}],
      link: {type: 'doc', id: 'reinforcement-learning/index'},
    },
    {
      type: 'category',
      label: 'Testing & Debugging',
      items: [{type: 'autogenerated', dirName: 'testing-debugging'}],
      link: {type: 'doc', id: 'testing-debugging/index'},
    },
    {
      type: 'category',
      label: 'Isaac',
      items: [{type: 'autogenerated', dirName: 'isaac'}],
      link: {type: 'doc', id: 'isaac/index'},
    },
    {
      type: 'category',
      label: 'VLA (Vision-Language-Action)',
      items: [{type: 'autogenerated', dirName: 'vla'}],
      link: {type: 'doc', id: 'vla/index'},
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [{type: 'autogenerated', dirName: 'capstone'}],
      link: {type: 'doc', id: 'capstone/index'},
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [{type: 'autogenerated', dirName: 'deployment'}],
      link: {type: 'doc', id: 'deployment/index'},
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [{type: 'autogenerated', dirName: 'appendices'}],
      link: {type: 'doc', id: 'appendices/index'},
    },
  ],
};

export default sidebars;